### ISSUE TITLE
fastddsgen build failed 

### ISSUE THREAD

**Issue by lazyze** [eProsima/Fast-DDS-Gen#123] opened 2022-06-08 02:22 UTC
Running the command "gradle assemble" or "./gradlew assemble"
(jdk version :java 17.0.3.1 2022-04-22 LTS)
(gradle version: Gradle 6.5)
yield a exception.

* What went wrong:
A problem occurred configuring root project 'fastddsgen'.
> Could not open proj generic class cache for build file '/home/zeli/Fast-DDS/src/fastddsgen/build.gradle' (/home/zeli/.gradle/caches/6.5/scripts/5zfbsee9uomyp34v31entjd61/proj6418c6d726070f323dbddda2aadc82ef).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 61

**Comment by EduPonz** [comment] 2022-06-08 05:09
Hi @lazyze ,

I believe this is a duplicate of #85. Would you mind checking with a lower version of Java SDK? In fact, we normally use 8, but that user verifies that 14 works as well.

**Closed by EduPonz** 2022-06-08 05:09 UTC
