### ISSUE TITLE
Unable to initialize main class when generating the source code with IDL file [14044]

### ISSUE THREAD

**Issue by yeah635007** [eProsima/Fast-DDS-Gen#102] opened 2022-03-07 13:23 UTC
root@LAPTOP-QR0CP0KH:~/dds/workspace_HelloWorld# ~/Fast-DDS/FastDDS-Gen/scripts/fastddsgen -python HelloWorld.idl
openjdk version "13.0.7" 2021-04-20
OpenJDK Runtime Environment (build 13.0.7+5-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 13.0.7+5-Ubuntu-0ubuntu120.04, mixed mode)
Error: Unable to initialize main class com.eprosima.fastdds.fastddsgen
Caused by: java.lang.NoClassDefFoundError: com/eprosima/idl/parser/typecode/TypeCode

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-07 14:42
Hi @yeah635007,

I have just installed in a clean Ubuntu Focal docker Fast DDS-Gen and OpenJDK 13. I have followed the instructions in the [documentation](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html#fast-dds-gen-installation) using the executable script `gradlew`. I have not been able to reproduce your issue. Which Fast DDS-Gen version are you using? Maybe you should clean your workspace, fetch the repository and rebuild Fast DDS-Gen.

**Comment by yeah635007** [comment] 2022-03-08 14:52
Fast DDS-Gen version is v2.1.1. gradle version is 6.4. java version is 13.0.7. I try again, but get a same result.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-09 07:03
Sorry, @yeah635007,

With the provided information I am unable to reproduce your issue. I leave you with the steps to reproduce what I have done. In case you want more support you will need to provide us with similar steps so we can reproduce the issue.

Here is the Dockerfile I have used:

```
FROM ubuntu:focal

ENV TZ=Europe/Madrid
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && \
    apt install -y git gcc openjdk-13-jdk
    
WORKDIR /home
RUN git clone --branch v2.1.1 https://github.com/eProsima/Fast-DDS-Gen.git && \
    cd Fast-DDS-Gen && \
    ./gradlew assemble
```

As you can see it installs the required dependencies and builds Fast DDS-Gen v2.1.1.

Running this docker, I can generate the TypeSupport for the following `HelloWorld.idl` IDL without any issue:

```
struct HelloWorld
{
    char a;
};
```

The command run is:

```
./Fast-DDS-Gen/scripts/fastddsgen -python HelloWorld.idl
```

You can try and follow these steps and see if it works for you. In case your issue is still happening, let me know what are you doing differently so I can reproduce at my side. If your issue is solved, please, proceed and close the issue.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-10-27 13:18
Not having received any feedback in the last few months I am going to proceed and close this issue. Please, feel free to reopen if the issue is still happening providing information about how to reproduce it.

**Closed by JLBuenoLopez-eProsima** 2022-10-27 13:18 UTC
Labels: need more info
