### ISSUE TITLE
When using IDL to generate code, FastDDsGen will report an error when the data structure key is a String map, and the generated code will not compile

### ISSUE THREAD

**Issue by huqin-RM** [eProsima/Fast-DDS-Gen#110] opened 2022-04-29 07:34 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

struct HelloWorld
{
      map<string, unsigned long long> data;

};

### Current behavior

Class com.eprosima.idl.parser.typecode.StringTypeCode has no such attribute: size in template context [struct_type if(ctx.anyCdr)_subtemplate anonymous if(!member.annotationNonSerialized)_subtemplate max_serialized_size elseif(typecode.isMapType)_subtemplate map_max_serialized_size]

### Steps to reproduce

fastddsgen HelloWorld.idl

### Fast DDS version/commit

d

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

UDPv4

**Comment by JLBuenoLopez-eProsima** [comment] 2022-04-29 07:57
Hi @huqin-RM 

I have moved the issue to the correct repository. This is a duplicate of #50 which was fixed in Fast DDS-Gen v2.1.0. Which version are you using? You can see the version running `fastddsgen -version`. Please, update your Fast DDS-Gen to solve your issue.

**Closed by JLBuenoLopez-eProsima** 2022-04-29 07:57 UTC
Labels: duplicate
